### ISSUE TITLE
unable to connect GPIB

### ISSUE THREAD

**Issue by WanManito** [javaNoviceProgrammer/jgpib#1]
Hello, when I use this library, I cannot connect to GPIB. The device is [hewlett-packard, E4403B, MY4510321]. What's the reason

**Comment by WanManito** [comment]
![image](https://user-images.githubusercontent.com/26118508/60176399-bb5cd000-9848-11e9-8e65-c6e659566a1a.png)

**Comment by WanManito** [comment]
![image](https://user-images.githubusercontent.com/26118508/60176519-17bfef80-9849-11e9-95b3-5b576ec0a9c1.png)

**Comment by javaNoviceProgrammer** [comment]
Did you install National Instruments visa drivers? I believe jgpib only works on Windows.

**Comment by WanManito** [comment]
I installed the driver of NI, and it was able to connect through TCP, but GPIB could not connect, and the connection address was confirmed by the software of NI，


It is possible to connect to GPIB through.net development





------------------ 原始邮件 ------------------
发件人: "javaNoviceProgrammer"<notifications@github.com>; 
发送时间: 2019年6月27日(星期四) 上午8:09
收件人: "javaNoviceProgrammer/jgpib"<jgpib@noreply.github.com>; 
抄送: "我亦是行人"<2430937882@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [javaNoviceProgrammer/jgpib] unable to connect GPIB (#1)




你安装了National Instruments签证驱动程序吗？我相信jgpib只适用于Windows。
 
- 
您收到此消息是因为您创作了该帖子。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。

**Comment by WanManito** [comment]
It turns out that I downloaded jvisaoneja. jar from sourceforge to develop it. I wonder if you have modified this package to make it capable of gpib communication

**Comment by WanManito** [comment]
Do you need to install NI 488.2 driver support when you use it

**Comment by WanManito** [comment]
I spent another day, but still could not connect it. The instrument model was [E4403B], and the last TCP test was successful [N9010B].The test platform was window10，
![image](https://user-images.githubusercontent.com/26118508/60256752-b78e8380-9904-11e9-88b0-5dff40acf9f2.png)
![image](https://user-images.githubusercontent.com/26118508/60257076-51eec700-9905-11e9-8920-05c1a2159797.png)
